# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controller.ui'
#
# Created: Sat Oct 10 17:16:43 2015
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Controller(object):
    def setupUi(self, Controller):
        Controller.setObjectName("Controller")
        Controller.resize(290, 495)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Controller.sizePolicy().hasHeightForWidth())
        Controller.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/sudodem-favicon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Controller.setWindowIcon(icon)
        self.gridLayout_3 = QtGui.QGridLayout(Controller)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.controllerTabs = QtGui.QTabWidget(Controller)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controllerTabs.sizePolicy().hasHeightForWidth())
        self.controllerTabs.setSizePolicy(sizePolicy)
        self.controllerTabs.setObjectName("controllerTabs")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadButton = QtGui.QPushButton(self.tab)
        self.loadButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 0))
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.saveButton = QtGui.QPushButton(self.tab)
        self.saveButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 0))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.inspectButton = QtGui.QPushButton(self.tab)
        self.inspectButton.setObjectName("inspectButton")
        self.horizontalLayout_2.addWidget(self.inspectButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(6)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.realTimeLabel = QtGui.QLabel(self.tab)
        self.realTimeLabel.setObjectName("realTimeLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.realTimeLabel)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.virtTimeLabel = QtGui.QLabel(self.tab)
        self.virtTimeLabel.setObjectName("virtTimeLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.virtTimeLabel)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.iterLabel = QtGui.QLabel(self.tab)
        self.iterLabel.setWordWrap(True)
        self.iterLabel.setObjectName("iterLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.iterLabel)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dtFixedRadio = QtGui.QRadioButton(self.tab)
        self.dtFixedRadio.setChecked(True)
        self.dtFixedRadio.setObjectName("dtFixedRadio")
        self.horizontalLayout.addWidget(self.dtFixedRadio)
        self.dtDynRadio = QtGui.QRadioButton(self.tab)
        self.dtDynRadio.setEnabled(False)
        self.dtDynRadio.setObjectName("dtDynRadio")
        self.horizontalLayout.addWidget(self.dtDynRadio)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.dtEdit = QtGui.QLineEdit(self.tab)
        self.dtEdit.setEnabled(False)
        self.dtEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dtEdit.setObjectName("dtEdit")
        self.verticalLayout.addWidget(self.dtEdit)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.verticalLayout)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.fileLabel = QtGui.QLabel(self.tab)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout_5.addWidget(self.fileLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playButton = QtGui.QPushButton(self.tab)
        self.playButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.playButton.setFont(font)
        self.playButton.setIconSize(QtCore.QSize(32, 32))
        self.playButton.setDefault(True)
        self.playButton.setFlat(False)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_3.addWidget(self.playButton)
        self.pauseButton = QtGui.QPushButton(self.tab)
        self.pauseButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pauseButton.setFont(font)
        self.pauseButton.setIconSize(QtCore.QSize(32, 32))
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_3.addWidget(self.pauseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.stepButton = QtGui.QPushButton(self.tab)
        self.stepButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton.sizePolicy().hasHeightForWidth())
        self.stepButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stepButton.setFont(font)
        self.stepButton.setIconSize(QtCore.QSize(32, 32))
        self.stepButton.setObjectName("stepButton")
        self.gridLayout_9.addWidget(self.stepButton, 0, 0, 1, 1)
        self.subStepCheckbox = QtGui.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.subStepCheckbox.setFont(font)
        self.subStepCheckbox.setObjectName("subStepCheckbox")
        self.gridLayout_9.addWidget(self.subStepCheckbox, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_9)
        self.reloadButton = QtGui.QPushButton(self.tab)
        self.reloadButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reloadButton.sizePolicy().hasHeightForWidth())
        self.reloadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.reloadButton.setFont(font)
        self.reloadButton.setIconSize(QtCore.QSize(32, 32))
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout_4.addWidget(self.reloadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.show3dButton = QtGui.QPushButton(self.tab)
        self.show3dButton.setCheckable(True)
        self.show3dButton.setObjectName("show3dButton")
        self.gridLayout_2.addWidget(self.show3dButton, 0, 0, 1, 1)
        self.referenceButton = QtGui.QPushButton(self.tab)
        self.referenceButton.setObjectName("referenceButton")
        self.gridLayout_2.addWidget(self.referenceButton, 0, 1, 1, 1)
        self.centerButton = QtGui.QPushButton(self.tab)
        self.centerButton.setObjectName("centerButton")
        self.gridLayout_2.addWidget(self.centerButton, 0, 2, 1, 1)
        self.xyzButton = QtGui.QPushButton(self.tab)
        self.xyzButton.setMinimumSize(QtCore.QSize(48, 48))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/XYZ.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.xyzButton.setIcon(icon1)
        self.xyzButton.setIconSize(QtCore.QSize(40, 40))
        self.xyzButton.setObjectName("xyzButton")
        self.gridLayout_2.addWidget(self.xyzButton, 1, 0, 1, 1)
        self.yzxButton = QtGui.QPushButton(self.tab)
        self.yzxButton.setMinimumSize(QtCore.QSize(48, 48))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/YZX.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yzxButton.setIcon(icon2)
        self.yzxButton.setIconSize(QtCore.QSize(40, 40))
        self.yzxButton.setObjectName("yzxButton")
        self.gridLayout_2.addWidget(self.yzxButton, 1, 1, 1, 1)
        self.zxyButton = QtGui.QPushButton(self.tab)
        self.zxyButton.setMinimumSize(QtCore.QSize(48, 48))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/ZXY.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zxyButton.setIcon(icon3)
        self.zxyButton.setIconSize(QtCore.QSize(40, 40))
        self.zxyButton.setObjectName("zxyButton")
        self.gridLayout_2.addWidget(self.zxyButton, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.controllerTabs.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.displayCombo = QtGui.QComboBox(self.tab_2)
        self.displayCombo.setObjectName("displayCombo")
        self.gridLayout_7.addWidget(self.displayCombo, 0, 0, 1, 1)
        self.displayArea = QtGui.QScrollArea(self.tab_2)
        self.displayArea.setWidgetResizable(True)
        self.displayArea.setObjectName("displayArea")
        self.displayAreaWidget = QtGui.QWidget(self.displayArea)
        self.displayAreaWidget.setGeometry(QtCore.QRect(0, 0, 284, 433))
        self.displayAreaWidget.setObjectName("displayAreaWidget")
        self.displayArea.setWidget(self.displayAreaWidget)
        self.gridLayout_7.addWidget(self.displayArea, 1, 0, 1, 1)
        self.controllerTabs.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.generatorCombo = QtGui.QComboBox(self.tab_4)
        self.generatorCombo.setObjectName("generatorCombo")
        self.gridLayout_5.addWidget(self.generatorCombo, 0, 0, 1, 1)
        self.generatorArea = QtGui.QScrollArea(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.generatorArea.sizePolicy().hasHeightForWidth())
        self.generatorArea.setSizePolicy(sizePolicy)
        self.generatorArea.setMinimumSize(QtCore.QSize(0, 0))
        self.generatorArea.setWidgetResizable(True)
        self.generatorArea.setObjectName("generatorArea")
        self.generatorAreaWidget = QtGui.QWidget(self.generatorArea)
        self.generatorAreaWidget.setGeometry(QtCore.QRect(0, 0, 500, 500))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatorAreaWidget.sizePolicy().hasHeightForWidth())
        self.generatorAreaWidget.setSizePolicy(sizePolicy)
        self.generatorAreaWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.generatorAreaWidget.setMaximumSize(QtCore.QSize(398, 336))
        self.generatorAreaWidget.setObjectName("generatorAreaWidget")
        self.generatorArea.setWidget(self.generatorAreaWidget)
        self.gridLayout_5.addWidget(self.generatorArea, 1, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.generatorMemoryCheck = QtGui.QCheckBox(self.tab_4)
        self.generatorMemoryCheck.setEnabled(False)
        self.generatorMemoryCheck.setCheckable(False)
        self.generatorMemoryCheck.setChecked(False)
        self.generatorMemoryCheck.setObjectName("generatorMemoryCheck")
        self.gridLayout_4.addWidget(self.generatorMemoryCheck, 0, 0, 1, 1)
        self.generatorFilenameEdit = QtGui.QLineEdit(self.tab_4)
        self.generatorFilenameEdit.setObjectName("generatorFilenameEdit")
        self.gridLayout_4.addWidget(self.generatorFilenameEdit, 0, 1, 1, 2)
        self.generatorAutoCheck = QtGui.QCheckBox(self.tab_4)
        self.generatorAutoCheck.setChecked(True)
        self.generatorAutoCheck.setObjectName("generatorAutoCheck")
        self.gridLayout_4.addWidget(self.generatorAutoCheck, 1, 0, 1, 2)
        self.generateButton = QtGui.QPushButton(self.tab_4)
        self.generateButton.setObjectName("generateButton")
        self.gridLayout_4.addWidget(self.generateButton, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.controllerTabs.addTab(self.tab_4, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pythonCombo = QtGui.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.pythonCombo.setFont(font)
        self.pythonCombo.setCursor(QtCore.Qt.IBeamCursor)
        self.pythonCombo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pythonCombo.setAutoFillBackground(False)
        self.pythonCombo.setEditable(True)
        self.pythonCombo.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.pythonCombo.setMinimumContentsLength(1)
        self.pythonCombo.setDuplicatesEnabled(False)
        self.pythonCombo.setObjectName("pythonCombo")
        self.verticalLayout_4.addWidget(self.pythonCombo)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.controllerTabs.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.controllerTabs, 0, 0, 1, 1)

        self.retranslateUi(Controller)
        self.controllerTabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.loadButton, QtCore.SIGNAL("clicked()"), Controller.loadSlot)
        QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL("clicked()"), Controller.saveSlot)
        QtCore.QObject.connect(self.dtFixedRadio, QtCore.SIGNAL("clicked()"), Controller.dtFixedSlot)
        QtCore.QObject.connect(self.dtDynRadio, QtCore.SIGNAL("clicked()"), Controller.dtDynSlot)
        QtCore.QObject.connect(self.dtEdit, QtCore.SIGNAL("editingFinished()"), Controller.dtEditedSlot)
        QtCore.QObject.connect(self.playButton, QtCore.SIGNAL("clicked()"), Controller.playSlot)
        QtCore.QObject.connect(self.pauseButton, QtCore.SIGNAL("clicked()"), Controller.pauseSlot)
        QtCore.QObject.connect(self.referenceButton, QtCore.SIGNAL("clicked()"), Controller.setReferenceSlot)
        QtCore.QObject.connect(self.centerButton, QtCore.SIGNAL("clicked()"), Controller.centerSlot)
        QtCore.QObject.connect(self.xyzButton, QtCore.SIGNAL("clicked()"), Controller.xyzSlot)
        QtCore.QObject.connect(self.yzxButton, QtCore.SIGNAL("clicked()"), Controller.yzxSlot)
        QtCore.QObject.connect(self.zxyButton, QtCore.SIGNAL("clicked()"), Controller.zxySlot)
        QtCore.QObject.connect(self.generateButton, QtCore.SIGNAL("clicked()"), Controller.generateSlot)
        QtCore.QObject.connect(self.dtEdit, QtCore.SIGNAL("textEdited(QString)"), Controller.dtEditNoupdateSlot)
        QtCore.QObject.connect(self.dtEdit, QtCore.SIGNAL("cursorPositionChanged(int,int)"), Controller.dtEditNoupdateSlot)
        QtCore.QObject.connect(self.generatorCombo, QtCore.SIGNAL("currentIndexChanged(QString)"), Controller.generatorComboSlot)
        QtCore.QObject.connect(self.displayCombo, QtCore.SIGNAL("currentIndexChanged(QString)"), Controller.displayComboSlot)
        QtCore.QObject.connect(self.pythonCombo, QtCore.SIGNAL("activated(QString)"), Controller.pythonComboSlot)
        QtCore.QObject.connect(self.inspectButton, QtCore.SIGNAL("clicked()"), Controller.inspectSlot)
        QtCore.QObject.connect(self.reloadButton, QtCore.SIGNAL("clicked()"), Controller.reloadSlot)
        QtCore.QObject.connect(self.stepButton, QtCore.SIGNAL("clicked()"), Controller.stepSlot)
        QtCore.QObject.connect(self.subStepCheckbox, QtCore.SIGNAL("stateChanged(int)"), Controller.subStepSlot)
        QtCore.QObject.connect(self.show3dButton, QtCore.SIGNAL("toggled(bool)"), Controller.show3dSlot)
        QtCore.QMetaObject.connectSlotsByName(Controller)

    def retranslateUi(self, Controller):
        Controller.setWindowTitle(QtGui.QApplication.translate("Controller", "SudoDEM", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("Controller", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Controller", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.inspectButton.setText(QtGui.QApplication.translate("Controller", "Inspect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Controller", "real", None, QtGui.QApplication.UnicodeUTF8))
        self.realTimeLabel.setText(QtGui.QApplication.translate("Controller", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Controller", "virt", None, QtGui.QApplication.UnicodeUTF8))
        self.virtTimeLabel.setText(QtGui.QApplication.translate("Controller", "00:000.000m000μ000n", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Controller", "iter", None, QtGui.QApplication.UnicodeUTF8))
        self.iterLabel.setText(QtGui.QApplication.translate("Controller", "#0, 0.0/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Controller", "Δt", None, QtGui.QApplication.UnicodeUTF8))
        self.dtFixedRadio.setText(QtGui.QApplication.translate("Controller", "fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.dtDynRadio.setText(QtGui.QApplication.translate("Controller", "time stepper", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("Controller", "[no file]", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("Controller", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("Controller", "▮▮", None, QtGui.QApplication.UnicodeUTF8))
        self.stepButton.setText(QtGui.QApplication.translate("Controller", "▶▮", None, QtGui.QApplication.UnicodeUTF8))
        self.subStepCheckbox.setText(QtGui.QApplication.translate("Controller", "sub-step", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadButton.setText(QtGui.QApplication.translate("Controller", "↻", None, QtGui.QApplication.UnicodeUTF8))
        self.show3dButton.setText(QtGui.QApplication.translate("Controller", "Show 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceButton.setText(QtGui.QApplication.translate("Controller", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.centerButton.setText(QtGui.QApplication.translate("Controller", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.controllerTabs.setTabText(self.controllerTabs.indexOf(self.tab), QtGui.QApplication.translate("Controller", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.controllerTabs.setTabText(self.controllerTabs.indexOf(self.tab_2), QtGui.QApplication.translate("Controller", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.generatorMemoryCheck.setText(QtGui.QApplication.translate("Controller", "memory slot", None, QtGui.QApplication.UnicodeUTF8))
        self.generatorFilenameEdit.setText(QtGui.QApplication.translate("Controller", "/tmp/scene.sudodem.gz", None, QtGui.QApplication.UnicodeUTF8))
        self.generatorAutoCheck.setText(QtGui.QApplication.translate("Controller", "open automatically", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setText(QtGui.QApplication.translate("Controller", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.controllerTabs.setTabText(self.controllerTabs.indexOf(self.tab_4), QtGui.QApplication.translate("Controller", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Controller", "<i>(Output appears in the terminal)</i>", None, QtGui.QApplication.UnicodeUTF8))
        self.controllerTabs.setTabText(self.controllerTabs.indexOf(self.tab_3), QtGui.QApplication.translate("Controller", "Python", None, QtGui.QApplication.UnicodeUTF8))

import img_rc
